import type { LearningObjective } from '@/domain/types';
import { trace } from './sources/traceability';

/**
 * LearningObjectives.
 *
 * Nivel 1 reproduce EXACTAMENTE el Apéndice A del contrato (IDs, títulos, orden, fuente,
 * modo de práctica y tiempo). Nivel 2/3/Referencia son curaduría P0-B derivada de las
 * secciones de fuente indicadas; nunca se presentan como deuda ni entran en Core Readiness.
 *
 * Decisión de curaduría (registrada en design/decisions.md):
 * LO-INT-003 pertenece al frente Entrevista (Apéndice A, sección A) y por tanto al denominador
 * de Core Readiness — Entrevista, aunque su contenido sea cross-track; se etiqueta 'cross-track'
 * para que aparezca también en las colecciones cross-track.
 */

// ---------------------------------------------------------------------------
// A. Entrevista esencial (Nivel 1)
// ---------------------------------------------------------------------------

const INTERVIEW_LEVEL_1: LearningObjective[] = [
  {
    id: 'LO-INT-001',
    title: 'Háblame de ti: pasado-presente-siguiente paso',
    track: 'interview',
    level: 1,
    priority: 'critical',
    order: 1,
    estimatedMinutes: 5,
    source: trace('ent-s3-respuesta'),
    sourceSummary: 'ENT §3',
    practiceMode: 'Oral + key points',
  },
  {
    id: 'LO-INT-002',
    title: 'Explicar por qué Derecho Penal',
    track: 'interview',
    level: 1,
    priority: 'critical',
    order: 2,
    estimatedMinutes: 5,
    source: trace('ent-s4-respuesta'),
    sourceSummary: 'ENT §4',
    practiceMode: 'Oral',
  },
  {
    id: 'LO-INT-003',
    title: 'Explicar experiencia penal real',
    track: 'interview',
    level: 1,
    priority: 'critical',
    order: 3,
    estimatedMinutes: 5,
    source: trace('ent-s5-respuesta'),
    sourceSummary: 'ENT §5',
    practiceMode: 'Oral cross-track',
  },
  {
    id: 'LO-INT-004',
    title: 'Decir con precisión qué no ha hecho en litigio',
    track: 'interview',
    level: 1,
    priority: 'critical',
    order: 4,
    estimatedMinutes: 5,
    source: trace('ent-s6-respuesta'),
    sourceSummary: 'ENT §6',
    practiceMode: 'Oral + follow-up',
  },
  {
    id: 'LO-INT-005',
    title: 'Explicar salida de TransUnion sin negatividad',
    track: 'interview',
    level: 1,
    priority: 'critical',
    order: 5,
    estimatedMinutes: 5,
    source: trace('ent-s7-respuesta'),
    sourceSummary: 'ENT §7',
    practiceMode: 'Oral',
  },
  {
    id: 'LO-INT-006',
    title: 'Contar error profesional y aprendizaje',
    track: 'interview',
    level: 1,
    priority: 'critical',
    order: 6,
    estimatedMinutes: 5,
    source: trace('ent-s14-respuesta'),
    sourceSummary: 'ENT §14',
    practiceMode: 'STAR oral',
  },
  {
    id: 'LO-INT-007',
    title: 'Explicar presión y términos',
    track: 'interview',
    level: 1,
    priority: 'critical',
    order: 7,
    estimatedMinutes: 5,
    source: trace('ent-s16-respuesta'),
    sourceSummary: 'ENT §16, §18',
    practiceMode: 'Oral',
  },
  {
    id: 'LO-INT-008',
    title: 'Comunicar brecha/debilidad con honestidad',
    track: 'interview',
    level: 1,
    priority: 'critical',
    order: 8,
    estimatedMinutes: 5,
    source: trace('ent-s13-respuesta'),
    sourceSummary: 'ENT §13',
    practiceMode: 'Oral',
  },
  {
    id: 'LO-INT-009',
    title: 'Explicar por qué contratarla',
    track: 'interview',
    level: 1,
    priority: 'critical',
    order: 9,
    estimatedMinutes: 5,
    source: trace('ent-s11-respuesta'),
    sourceSummary: 'ENT §11',
    practiceMode: 'Oral',
  },
  {
    id: 'LO-INT-010',
    title: 'Responder salario y disponibilidad',
    track: 'interview',
    level: 1,
    priority: 'critical',
    order: 10,
    estimatedMinutes: 5,
    source: trace('ent-s35-respuesta'),
    sourceSummary: 'ENT §34-36',
    practiceMode: 'Oral',
  },
  {
    id: 'LO-INT-011',
    title: 'Explicar contratos temporales y juzgados',
    track: 'interview',
    level: 1,
    priority: 'high',
    order: 11,
    estimatedMinutes: 5,
    source: trace('ent-s8-respuesta'),
    sourceSummary: 'ENT §8-10',
    practiceMode: 'Oral',
  },
  {
    id: 'LO-INT-012',
    title: 'Recuperar STAR esenciales',
    track: 'interview',
    level: 1,
    priority: 'high',
    order: 12,
    estimatedMinutes: 10,
    source: trace('ent-s42-a'),
    sourceSummary: 'ENT §42',
    practiceMode: 'STAR oral',
  },
];

// ---------------------------------------------------------------------------
// B. Penal esencial (Nivel 1)
// ---------------------------------------------------------------------------

const PENAL_LEVEL_1: LearningObjective[] = [
  {
    id: 'LO-PEN-001',
    title: 'Explicar experiencia propia en ejecución de penas',
    track: 'penal',
    level: 1,
    priority: 'critical',
    order: 1,
    estimatedMinutes: 5,
    source: trace('pen-s55-que-hacias'),
    sourceSummary: 'PEN §39, §43-44, §55',
    practiceMode: 'Oral cross-track',
  },
  {
    id: 'LO-PEN-002',
    title: 'Definir conducta punible',
    track: 'penal',
    level: 1,
    priority: 'critical',
    order: 2,
    estimatedMinutes: 2,
    source: trace('pen-s3-estructura'),
    sourceSummary: 'PEN §3',
    practiceMode: 'Flashcard + recall',
  },
  {
    id: 'LO-PEN-003',
    title: 'Distinguir tipicidad, antijuridicidad y culpabilidad',
    track: 'penal',
    level: 1,
    priority: 'critical',
    order: 3,
    estimatedMinutes: 5,
    source: trace('pen-s3-corta'),
    sourceSummary: 'PEN §3, §54',
    practiceMode: 'Distinción + quiz',
    allowedPrerequisiteObjectiveIds: ['LO-PEN-002'],
  },
  {
    id: 'LO-PEN-004',
    title: 'Distinguir dolo y culpa',
    track: 'penal',
    level: 1,
    priority: 'critical',
    order: 4,
    estimatedMinutes: 5,
    source: trace('pen-s5-respuesta'),
    sourceSummary: 'PEN §5, §54',
    practiceMode: 'Recall + aplicación breve',
  },
  {
    id: 'LO-PEN-005',
    title: 'Explicar tentativa',
    track: 'penal',
    level: 1,
    priority: 'critical',
    order: 5,
    estimatedMinutes: 5,
    source: trace('pen-s7-tentativa'),
    sourceSummary: 'PEN §7, §54',
    practiceMode: 'Recall + aplicación',
  },
  {
    id: 'LO-PEN-006',
    title: 'Distinguir autor, coautor y cómplice',
    track: 'penal',
    level: 1,
    priority: 'critical',
    order: 6,
    estimatedMinutes: 5,
    source: trace('pen-s8-respuesta'),
    sourceSummary: 'PEN §8, §54',
    practiceMode: 'Distinción',
  },
  {
    id: 'LO-PEN-007',
    title: 'Recordar mapa básico del proceso',
    track: 'penal',
    level: 1,
    priority: 'critical',
    order: 7,
    estimatedMinutes: 5,
    source: trace('pen-s12-formula'),
    sourceSummary: 'PEN §12',
    practiceMode: 'Recall ordenado',
  },
  {
    id: 'LO-PEN-008',
    title: 'Distinguir juez de garantías y conocimiento',
    track: 'penal',
    level: 1,
    priority: 'critical',
    order: 8,
    estimatedMinutes: 5,
    source: trace('pen-s15-corta'),
    sourceSummary: 'PEN §15',
    practiceMode: 'Distinción',
  },
  {
    id: 'LO-PEN-009',
    title: 'Analizar captura y flagrancia básica',
    track: 'penal',
    level: 1,
    priority: 'critical',
    order: 9,
    estimatedMinutes: 5,
    source: trace('pen-s17-flagrancia'),
    sourceSummary: 'PEN §16-17',
    practiceMode: 'Quiz/aplicación',
  },
  {
    id: 'LO-PEN-010',
    title: 'Distinguir imputación y acusación',
    track: 'penal',
    level: 1,
    priority: 'critical',
    order: 10,
    estimatedMinutes: 5,
    source: trace('pen-s19-respuesta'),
    sourceSummary: 'PEN §18-19, §54',
    practiceMode: 'Flashcard + quiz',
  },
  {
    id: 'LO-PEN-011',
    title: 'Explicar medida de aseguramiento',
    track: 'penal',
    level: 1,
    priority: 'critical',
    order: 11,
    estimatedMinutes: 5,
    source: trace('pen-s21-requisitos'),
    sourceSummary: 'PEN §21, §38',
    practiceMode: 'Recall + aplicación',
  },
  {
    id: 'LO-PEN-012',
    title: 'Explicar teoría del caso',
    track: 'penal',
    level: 1,
    priority: 'high',
    order: 12,
    estimatedMinutes: 2,
    source: trace('pen-s25-teoria'),
    sourceSummary: 'PEN §25, §54',
    practiceMode: 'Recall',
  },
  {
    id: 'LO-PEN-013',
    title: 'Identificar estándar de condena',
    track: 'penal',
    level: 1,
    priority: 'critical',
    order: 13,
    estimatedMinutes: 2,
    source: trace('pen-s31-estandar'),
    sourceSummary: 'PEN §31, §54',
    practiceMode: 'Recall',
  },
  {
    id: 'LO-PEN-014',
    title: 'Explicar hábeas corpus',
    track: 'penal',
    level: 1,
    priority: 'critical',
    order: 14,
    estimatedMinutes: 5,
    source: trace('pen-s37-habeas'),
    sourceSummary: 'PEN §37, §54',
    practiceMode: 'Recall/oral',
  },
  {
    id: 'LO-PEN-015',
    title: 'Explicar juez de ejecución de penas',
    track: 'penal',
    level: 1,
    priority: 'critical',
    order: 15,
    estimatedMinutes: 5,
    source: trace('pen-s39-respuesta'),
    sourceSummary: 'PEN §39, §54',
    practiceMode: 'Oral',
  },
  {
    id: 'LO-PEN-016',
    title: 'Explicar libertad condicional y redención conceptual',
    track: 'penal',
    level: 1,
    priority: 'critical',
    order: 16,
    estimatedMinutes: 5,
    source: trace('pen-s42-condicional'),
    sourceSummary: 'PEN §42-43',
    practiceMode: 'Distinción',
  },
  {
    id: 'LO-PEN-017',
    title: 'Razonar respuesta técnica no recordada',
    track: 'penal',
    level: 1,
    priority: 'high',
    order: 17,
    estimatedMinutes: 5,
    source: trace('pen-s57-patron'),
    sourceSummary: 'PEN §48, §57; ENT §44-45',
    practiceMode: 'Oral cross-track',
  },
];

// ---------------------------------------------------------------------------
// C. Cross-track (Nivel 1)
// ---------------------------------------------------------------------------

const CROSS_LEVEL_1: LearningObjective[] = [
  {
    id: 'LO-X-001',
    title: 'Conectar experiencia de ejecución con candidatura Penal sin exagerar litigio',
    track: 'cross-track',
    level: 1,
    priority: 'critical',
    order: 1,
    estimatedMinutes: 5,
    source: trace('ent-s5-brecha'),
    sourceSummary: 'ENT §5-6, §32-33; PEN §39, §55-56',
    practiceMode: 'Oral + follow-up',
    interleaveAfterObjectiveId: 'LO-INT-003',
  },
  {
    id: 'LO-X-002',
    title: 'Explicar hábeas corpus desde experiencia y concepto',
    track: 'cross-track',
    level: 1,
    priority: 'high',
    order: 2,
    estimatedMinutes: 5,
    source: trace('pen-s37-respuesta'),
    sourceSummary: 'ENT §3, §5; PEN §37',
    practiceMode: 'Oral + recall',
    interleaveAfterObjectiveId: 'LO-PEN-014',
  },
  {
    id: 'LO-X-003',
    title: 'Responder una pregunta técnica sin inventar artículo',
    track: 'cross-track',
    level: 1,
    priority: 'high',
    order: 3,
    estimatedMinutes: 5,
    source: trace('ent-s44-formula'),
    sourceSummary: 'ENT §21, §44-45; PEN §57',
    practiceMode: 'Oral guiada',
    interleaveAfterObjectiveId: 'LO-PEN-010',
  },
];

// ---------------------------------------------------------------------------
// Nivel 2 — muy conveniente (P0-B). Disponible, nunca deuda.
// ---------------------------------------------------------------------------

const INTERVIEW_LEVEL_2: LearningObjective[] = [
  {
    id: 'LO-INT-201',
    title: 'Contar una situación difícil con un superior',
    track: 'interview',
    level: 2,
    priority: 'high',
    order: 1,
    estimatedMinutes: 5,
    source: trace('ent-s15-respuesta'),
    sourceSummary: 'ENT §15',
    practiceMode: 'STAR oral',
  },
  {
    id: 'LO-INT-202',
    title: 'Responder cómo reacciona a una crítica',
    track: 'interview',
    level: 2,
    priority: 'medium',
    order: 2,
    estimatedMinutes: 5,
    source: trace('ent-s30-respuesta'),
    sourceSummary: 'ENT §30',
    practiceMode: 'Oral',
  },
  {
    id: 'LO-INT-203',
    title: 'Explicar una decisión profesional difícil',
    track: 'interview',
    level: 2,
    priority: 'medium',
    order: 3,
    estimatedMinutes: 5,
    source: trace('ent-s28-respuesta'),
    sourceSummary: 'ENT §28',
    practiceMode: 'Oral',
  },
  {
    id: 'LO-INT-204',
    title: 'Manejar un cliente difícil',
    track: 'interview',
    level: 2,
    priority: 'medium',
    order: 4,
    estimatedMinutes: 5,
    source: trace('ent-s23-respuesta'),
    sourceSummary: 'ENT §23',
    practiceMode: 'Oral',
  },
  {
    id: 'LO-INT-205',
    title: 'Explicar cómo trabaja en equipo',
    track: 'interview',
    level: 2,
    priority: 'medium',
    order: 5,
    estimatedMinutes: 5,
    source: trace('ent-s29-respuesta'),
    sourceSummary: 'ENT §29',
    practiceMode: 'Oral',
  },
  {
    id: 'LO-INT-206',
    title: 'Responder dilemas éticos adicionales',
    track: 'interview',
    level: 2,
    priority: 'high',
    order: 6,
    estimatedMinutes: 5,
    source: trace('ent-s20-respuesta'),
    sourceSummary: 'ENT §20, §24-25',
    practiceMode: 'Oral situacional',
  },
  {
    id: 'LO-INT-207',
    title: 'Responder por la carga laboral del nuevo rol',
    track: 'interview',
    level: 2,
    priority: 'medium',
    order: 7,
    estimatedMinutes: 5,
    source: trace('ent-s37-respuesta'),
    sourceSummary: 'ENT §37',
    practiceMode: 'Oral',
  },
  {
    id: 'LO-INT-208',
    title: 'Responder dónde se ve en cinco años',
    track: 'interview',
    level: 2,
    priority: 'medium',
    order: 8,
    estimatedMinutes: 5,
    source: trace('ent-s27-respuesta'),
    sourceSummary: 'ENT §27',
    practiceMode: 'Oral',
  },
  {
    id: 'LO-INT-209',
    title: 'Explicar cómo aprende algo que no sabe',
    track: 'interview',
    level: 2,
    priority: 'medium',
    order: 9,
    estimatedMinutes: 5,
    source: trace('ent-s19-respuesta'),
    sourceSummary: 'ENT §19',
    practiceMode: 'Oral',
  },
  {
    id: 'LO-INT-210',
    title: 'Preparar las preguntas al despacho',
    track: 'interview',
    level: 2,
    priority: 'high',
    order: 10,
    estimatedMinutes: 5,
    source: trace('ent-s41-p1'),
    sourceSummary: 'ENT §40-41',
    practiceMode: 'Selección y ensayo',
  },
];

const PENAL_LEVEL_2: LearningObjective[] = [
  {
    id: 'LO-PEN-201',
    title: 'Reconocer causales de ausencia de responsabilidad',
    track: 'penal',
    level: 2,
    priority: 'high',
    order: 1,
    estimatedMinutes: 5,
    source: trace('pen-s10-causales'),
    sourceSummary: 'PEN §10',
    practiceMode: 'Recall + distinción',
  },
  {
    id: 'LO-PEN-202',
    title: 'Explicar inimputabilidad sin confundirla con impunidad',
    track: 'penal',
    level: 2,
    priority: 'medium',
    order: 2,
    estimatedMinutes: 5,
    source: trace('pen-s11-inimputabilidad'),
    sourceSummary: 'PEN §11',
    practiceMode: 'Distinción',
  },
  {
    id: 'LO-PEN-203',
    title: 'Distinguir denuncia y querella',
    track: 'penal',
    level: 2,
    priority: 'medium',
    order: 3,
    estimatedMinutes: 2,
    source: trace('pen-s13-respuesta'),
    sourceSummary: 'PEN §13',
    practiceMode: 'Distinción',
  },
  {
    id: 'LO-PEN-204',
    title: 'Distinguir indiciado, imputado, acusado y condenado',
    track: 'penal',
    level: 2,
    priority: 'high',
    order: 4,
    estimatedMinutes: 5,
    source: trace('pen-s14-respuesta'),
    sourceSummary: 'PEN §14',
    practiceMode: 'Distinción',
  },
  {
    id: 'LO-PEN-205',
    title: 'Explicar hechos jurídicamente relevantes',
    track: 'penal',
    level: 2,
    priority: 'high',
    order: 5,
    estimatedMinutes: 5,
    source: trace('pen-s20-buena'),
    sourceSummary: 'PEN §20',
    practiceMode: 'Recall',
  },
  {
    id: 'LO-PEN-206',
    title: 'Explicar audiencia de acusación y descubrimiento probatorio',
    track: 'penal',
    level: 2,
    priority: 'medium',
    order: 6,
    estimatedMinutes: 5,
    source: trace('pen-s23-descubrimiento'),
    sourceSummary: 'PEN §22-23',
    practiceMode: 'Recall',
  },
  {
    id: 'LO-PEN-207',
    title: 'Explicar la audiencia preparatoria',
    track: 'penal',
    level: 2,
    priority: 'medium',
    order: 7,
    estimatedMinutes: 5,
    source: trace('pen-s24-corta'),
    sourceSummary: 'PEN §24',
    practiceMode: 'Recall',
  },
  {
    id: 'LO-PEN-208',
    title: 'Distinguir EMP, evidencia física y prueba de juicio',
    track: 'penal',
    level: 2,
    priority: 'high',
    order: 8,
    estimatedMinutes: 5,
    source: trace('pen-s26-frase'),
    sourceSummary: 'PEN §26',
    practiceMode: 'Distinción',
  },
  {
    id: 'LO-PEN-209',
    title: 'Explicar cadena de custodia y sus fallas',
    track: 'penal',
    level: 2,
    priority: 'medium',
    order: 9,
    estimatedMinutes: 5,
    source: trace('pen-s27-cadena'),
    sourceSummary: 'PEN §27',
    practiceMode: 'Recall + aplicación',
  },
  {
    id: 'LO-PEN-210',
    title: 'Explicar prueba ilícita y cláusula de exclusión',
    track: 'penal',
    level: 2,
    priority: 'medium',
    order: 10,
    estimatedMinutes: 5,
    source: trace('pen-s28-respuesta'),
    sourceSummary: 'PEN §28',
    practiceMode: 'Recall',
  },
  {
    id: 'LO-PEN-211',
    title: 'Reconocer principios probatorios del juicio',
    track: 'penal',
    level: 2,
    priority: 'medium',
    order: 11,
    estimatedMinutes: 5,
    source: trace('pen-s29-inmediacion'),
    sourceSummary: 'PEN §29',
    practiceMode: 'Recall',
  },
  {
    id: 'LO-PEN-212',
    title: 'Distinguir pertinencia y admisibilidad',
    track: 'penal',
    level: 2,
    priority: 'medium',
    order: 12,
    estimatedMinutes: 5,
    source: trace('pen-s30-pertinencia'),
    sourceSummary: 'PEN §30',
    practiceMode: 'Distinción',
  },
  {
    id: 'LO-PEN-213',
    title: 'Explicar derechos de la víctima',
    track: 'penal',
    level: 2,
    priority: 'medium',
    order: 13,
    estimatedMinutes: 5,
    source: trace('pen-s35-abogado'),
    sourceSummary: 'PEN §35',
    practiceMode: 'Recall',
  },
  {
    id: 'LO-PEN-214',
    title: 'Explicar deberes de la defensa técnica',
    track: 'penal',
    level: 2,
    priority: 'medium',
    order: 14,
    estimatedMinutes: 5,
    source: trace('pen-s36-defensa'),
    sourceSummary: 'PEN §36',
    practiceMode: 'Recall',
  },
  {
    id: 'LO-PEN-215',
    title: 'Explicar prisión domiciliaria como sustitutiva',
    track: 'penal',
    level: 2,
    priority: 'high',
    order: 15,
    estimatedMinutes: 5,
    source: trace('pen-s40-domiciliaria'),
    sourceSummary: 'PEN §40',
    practiceMode: 'Distinción',
  },
  {
    id: 'LO-PEN-216',
    title: 'Explicar suspensión de la ejecución de la pena',
    track: 'penal',
    level: 2,
    priority: 'medium',
    order: 16,
    estimatedMinutes: 5,
    source: trace('pen-s41-suspension'),
    sourceSummary: 'PEN §41',
    practiceMode: 'Recall',
  },
  {
    id: 'LO-PEN-217',
    title: 'Explicar presunción de inocencia e in dubio pro reo',
    track: 'penal',
    level: 2,
    priority: 'high',
    order: 17,
    estimatedMinutes: 5,
    source: trace('pen-s4-presuncion'),
    sourceSummary: 'PEN §4',
    practiceMode: 'Recall',
  },
];

// ---------------------------------------------------------------------------
// Nivel 3 — profundización (P0-B).
// ---------------------------------------------------------------------------

const PENAL_LEVEL_3: LearningObjective[] = [
  {
    id: 'LO-PEN-301',
    title: 'Explicar concurso de conductas punibles',
    track: 'penal',
    level: 3,
    priority: 'medium',
    order: 1,
    estimatedMinutes: 5,
    source: trace('pen-s9-concurso'),
    sourceSummary: 'PEN §9',
    practiceMode: 'Distinción',
  },
  {
    id: 'LO-PEN-302',
    title: 'Explicar posición de garante',
    track: 'penal',
    level: 3,
    priority: 'medium',
    order: 2,
    estimatedMinutes: 5,
    source: trace('pen-s6-garante'),
    sourceSummary: 'PEN §6',
    practiceMode: 'Recall',
  },
  {
    id: 'LO-PEN-303',
    title: 'Explicar preclusión',
    track: 'penal',
    level: 3,
    priority: 'medium',
    order: 3,
    estimatedMinutes: 2,
    source: trace('pen-s32-concepto'),
    sourceSummary: 'PEN §32',
    practiceMode: 'Recall',
  },
  {
    id: 'LO-PEN-304',
    title: 'Explicar principio de oportunidad',
    track: 'penal',
    level: 3,
    priority: 'medium',
    order: 4,
    estimatedMinutes: 5,
    source: trace('pen-s33-oportunidad'),
    sourceSummary: 'PEN §33',
    practiceMode: 'Recall',
  },
  {
    id: 'LO-PEN-305',
    title: 'Explicar preacuerdos y aceptación de cargos',
    track: 'penal',
    level: 3,
    priority: 'medium',
    order: 5,
    estimatedMinutes: 5,
    source: trace('pen-s34-preacuerdos'),
    sourceSummary: 'PEN §34',
    practiceMode: 'Recall',
  },
  {
    id: 'LO-PEN-306',
    title: 'Explicar cuándo una irregularidad genera nulidad',
    track: 'penal',
    level: 3,
    priority: 'medium',
    order: 6,
    estimatedMinutes: 5,
    source: trace('pen-s46-nulidad'),
    sourceSummary: 'PEN §46',
    practiceMode: 'Recall',
  },
  {
    id: 'LO-PEN-307',
    title: 'Reconocer recursos básicos',
    track: 'penal',
    level: 3,
    priority: 'medium',
    order: 7,
    estimatedMinutes: 2,
    source: trace('pen-s47-apelacion'),
    sourceSummary: 'PEN §47',
    practiceMode: 'Recall',
  },
  {
    id: 'LO-PEN-308',
    title: 'Explicar prescripción sin improvisar cálculos',
    track: 'penal',
    level: 3,
    priority: 'medium',
    order: 8,
    estimatedMinutes: 5,
    source: trace('pen-s45-calculo'),
    sourceSummary: 'PEN §45',
    practiceMode: 'Recall + criterio',
  },
];

// ---------------------------------------------------------------------------
// Referencia — consulta. No integra plan activo ni indicador principal.
// ---------------------------------------------------------------------------

const REFERENCE: LearningObjective[] = [
  {
    id: 'LO-REF-001',
    title: 'Artículos que vale la pena tener ubicados',
    track: 'penal',
    level: 'reference',
    priority: 'reference',
    order: 1,
    estimatedMinutes: 10,
    source: trace('pen-s58-aviso'),
    sourceSummary: 'PEN §58',
    practiceMode: 'Consulta',
  },
  {
    id: 'LO-REF-002',
    title: 'Estructura del Derecho Penal y normas centrales',
    track: 'penal',
    level: 'reference',
    priority: 'reference',
    order: 2,
    estimatedMinutes: 5,
    source: trace('pen-s2-sustancial'),
    sourceSummary: 'PEN §2',
    practiceMode: 'Consulta',
  },
];

export const LEARNING_OBJECTIVES: LearningObjective[] = [
  ...INTERVIEW_LEVEL_1,
  ...PENAL_LEVEL_1,
  ...CROSS_LEVEL_1,
  ...INTERVIEW_LEVEL_2,
  ...PENAL_LEVEL_2,
  ...PENAL_LEVEL_3,
  ...REFERENCE,
];

const BY_ID = new Map(LEARNING_OBJECTIVES.map((o) => [o.id, o]));

export function getObjective(id: string): LearningObjective | undefined {
  return BY_ID.get(id);
}

export function requireObjective(id: string): LearningObjective {
  const objective = BY_ID.get(id);
  if (!objective) throw new Error(`LearningObjective desconocido: ${id}`);
  return objective;
}

export const LEVEL_1_OBJECTIVES = LEARNING_OBJECTIVES.filter((o) => o.level === 1);

/**
 * Secuencia por defecto del Apéndice A: empezar por Entrevista esencial y experiencia real;
 * intercalar Penal tras los primeros objetivos de entrevista, y los cross-track en el punto
 * declarado por el Apéndice A.
 */
export const DEFAULT_LEVEL_1_SEQUENCE: string[] = (() => {
  const interview = INTERVIEW_LEVEL_1.map((o) => o.id);
  const penal = PENAL_LEVEL_1.map((o) => o.id);
  const sequence: string[] = [];
  // Primeros tres objetivos de entrevista, sin teoría penal por delante.
  sequence.push(interview[0], interview[1], interview[2]);
  // Cross-track declarado tras INT-003.
  sequence.push('LO-X-001');
  // A partir de aquí se intercala Penal manteniendo la ponderación Entrevista 65 / Penal 35.
  let penalIndex = 0;
  for (let i = 3; i < interview.length; i += 1) {
    sequence.push(interview[i]);
    for (let k = 0; k < 2 && penalIndex < penal.length; k += 1) {
      const penalId = penal[penalIndex];
      sequence.push(penalId);
      penalIndex += 1;
      const interleaved = CROSS_LEVEL_1.find((c) => c.interleaveAfterObjectiveId === penalId);
      if (interleaved) sequence.push(interleaved.id);
    }
  }
  while (penalIndex < penal.length) {
    const penalId = penal[penalIndex];
    sequence.push(penalId);
    penalIndex += 1;
    const interleaved = CROSS_LEVEL_1.find((c) => c.interleaveAfterObjectiveId === penalId);
    if (interleaved) sequence.push(interleaved.id);
  }
  for (const cross of CROSS_LEVEL_1) {
    if (!sequence.includes(cross.id)) sequence.push(cross.id);
  }
  return sequence;
})();
